MODEL_TYPES = {
    "arch": "T:Arch",
    "triplearch": "T:TripleArch",
    "candy cane": "T:CandyCane",
    "cross": "T:Cross",
    "cube": "T:Cube",
    "flood": "T:Flood",
    "icicles": "T:Icicles",
    "line": "T:Line",
    "horizontal_line": "T:HLine",
    "vertical_line": "T:VLine",
    "matrix": "T:Matrix",
    "matrix_horizontal": "T:Matrix_Horizontal",
    "matrix_column": "T:Matrix_Column",
    "matrix_pole": "T:Matrix_Pole",
    "DmxMovingHeadAdv" : "T:MH",
    "singing": "T:Singing",
    "snowflake": "T:Snowflake",
    "sphere": "T:Sphere",
    "spinner": "T:Spinner",
    "star": "T:Star",
    "tune_to": "T:TuneTo",
    "tree": "T:Tree",
    "spiral_tree": "T:Spiral_Tree",
    "mega_tree": "T:Mega_Tree",
    "window_frame": "T:WindowFrame",
    "wreath": "T:Wreath"
}